site:
  title: Morphia Docs
  start_page: landing::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/MorphiaOrg/morphia
    branches: [ master, 2.2.x, 2.1.x, 1.6.x ]
    start_path: docs
  - url: https://github.com/MorphiaOrg/critter
    branches: [ 4.1.x, master ]
    start_path: docs

ui:
  bundle:
    url: node_modules/@djencks/javadoc-ui/build/javadoc-ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

#output:
#  clean: true

runtime:
  fetch: true

asciidoc:
  attributes:
    docsRef: http://docs.mongodb.org/manual
