site:
  title: Morphia Docs
  start_page: landing::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://github.com/MorphiaOrg/morphia
    branches: [ master, 2.5.x, 2.4.x, 2.3.x, 1.6.x ] ### morphia branches
    start_path: docs
  - url: https://github.com/MorphiaOrg/critter
    branches: [ 4.4.x, 4.3.x ]
    start_path: docs

ui:
  bundle:
    url: node_modules/@djencks/javadoc-ui/build/javadoc-ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

runtime:
  fetch: true

asciidoc:
  attributes:
    docsRef: http://docs.mongodb.org/manual
