baseURL = "https://morphia.dev/"
languageCode = "en-us"
title = "Morphia Documentation"
theme = "morphia"
disableHugoGeneratorInject = true
enableRobotsTXT = true
relativeURLs = true

[params]
  description = "Morphia — MongoDB Object-Document Mapping for the JVM"
  github = "https://github.com/MorphiaOrg/morphia"
  issues = "https://github.com/MorphiaOrg/morphia/issues"
  community = "https://discord.gg/saZsJescBa"
  commonhaus = "https://www.commonhaus.org"
  commonhausTrademarks = "https://www.commonhaus.org/trademarks/"
  commonhausTrademarkPolicy = "https://www.commonhaus.org/policies/trademark-policy/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        disable = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
