# Morphia Docs — Hugo build system
# Uncomment for verbose debug output:
# __ORIGINAL_SHELL:=$(SHELL)
# SHELL=$(warning [[ Building $@$(if $<, (from $<))$(if $?, ($? newer)) ]] )$(TIME) $(__ORIGINAL_SHELL)

GH_PAGES = gh_pages
HUGO_OUT = build/site
BRANCHES = master 2.5.x 2.4.x
# Released (non-snapshot) versions for which we download javadoc
JAVADOC_VERSIONS = $(shell awk '/snapshot: false/{f=1} f && /version:/{gsub(/[^0-9.]/,""); if($$0!="")print; f=0}' data/versions.yaml 2>/dev/null | sort -u)

JAVADOC_BASE_URL ?= https://repo1.maven.org/maven2/dev/morphia/morphia/morphia-core

default: site

# ── Content staging ───────────────────────────────────────────────────────────
# Symlink content/morphia/<version> → branches/<branch> for every branch.
# The master (snapshot) branch uses its version number as the URL segment
# (e.g. "3.0"), so the URL won't change when the snapshot is released.

stage-content:
	@mkdir -p content/morphia
	@for BRANCH in $(BRANCHES); do \
	  [ -f "branches/$$BRANCH/.version" ] || continue ; \
	  VER=$$(cat "branches/$$BRANCH/.version" | tr -d '[:space:]') ; \
	  TARGET="content/morphia/$$VER" ; \
	  [ -e "$$TARGET" ] || ln -sf "../../branches/$$BRANCH" "$$TARGET" ; \
	done
	@echo "Content staged."

# ── Version data ──────────────────────────────────────────────────────────────
# Regenerate data/versions.yaml from .version files in branches/.
data/versions.yaml: $(wildcard branches/*/.version)
	@echo "# Generated by 'make data/versions.yaml' — do not edit by hand." > $@
	@LATEST=$$(for B in $(BRANCHES); do \
	    [ "$$B" = "master" ] && continue ; \
	    cat "branches/$$B/.version" 2>/dev/null ; \
	  done | sort -V | tail -1 | tr -d '[:space:]') ; \
	echo "latestVersion: \"$$LATEST\"" >> $@ ; \
	echo "versions:" >> $@ ; \
	for BRANCH in $(BRANCHES); do \
	  [ -f "branches/$$BRANCH/.version" ] || continue ; \
	  VER=$$(cat "branches/$$BRANCH/.version" | tr -d '[:space:]') ; \
	  if [ "$$BRANCH" = "master" ]; then \
	    printf "  - branch: \"%s\"\n    version: \"%s\"\n    display: \"%s\"\n    latest: false\n    snapshot: true\n" \
	      "$$BRANCH" "$$VER" "$$BRANCH" >> $@ ; \
	  elif [ "$$VER" = "$$LATEST" ]; then \
	    printf "  - branch: \"%s\"\n    version: \"%s\"\n    display: \"%s\"\n    latest: true\n    snapshot: false\n" \
	      "$$BRANCH" "$$VER" "$$VER" >> $@ ; \
	  else \
	    printf "  - branch: \"%s\"\n    version: \"%s\"\n    display: \"%s\"\n    latest: false\n    snapshot: false\n" \
	      "$$BRANCH" "$$VER" "$$VER" >> $@ ; \
	  fi ; \
	done
	@echo "Generated $@"

# ── Javadoc ───────────────────────────────────────────────────────────────────
# Download and unpack the javadoc JAR for each released version.
# The javadoc tree is generated and not committed; it lives at:
#   build/site/morphia/<version>/javadoc/
javadoc/%: $(HUGO_OUT)
	@echo "Fetching javadoc for version $*..."
	@mkdir -p build/javadoc-jars
	@JAR_URL="$(JAVADOC_BASE_URL)/$*/morphia-core-$*-javadoc.jar" ; \
	TMP="build/javadoc-jars/morphia-core-$*-javadoc.jar" ; \
	if [ ! -f "$$TMP" ]; then \
	  curl -fsSL "$$JAR_URL" -o "$$TMP" || { echo "  WARNING: javadoc not available for $*"; rm -f "$$TMP"; exit 0; } ; \
	fi ; \
	[ -f "$$TMP" ] && unzip -q -o "$$TMP" -d "$(HUGO_OUT)/morphia/$*/javadoc" ; \
	echo "  Unpacked javadoc for $* → $(HUGO_OUT)/morphia/$*/javadoc"

javadocs: $(patsubst %,javadoc/%,$(JAVADOC_VERSIONS))

# ── Hugo build ────────────────────────────────────────────────────────────────
$(HUGO_OUT):
	@mkdir -p $@

site: stage-content data/versions.yaml
	@hugo --destination $(HUGO_OUT) --cleanDestinationDir
	@touch $(HUGO_OUT)/.nojekyll
	@echo "Site built → $(HUGO_OUT)"

# Full build including javadoc (used before publishing)
publish-build: site javadocs

# ── gh-pages ─────────────────────────────────────────────────────────────────
$(GH_PAGES): .PHONY
	@[ ! -d $@ ] && git clone $${REMOTE_REPO} -b gh-pages --depth 1 --no-single-branch $(GH_PAGES) || true
	@git -C $@ reset --hard --quiet && git -C $@ pull --all --quiet

$(GH_PAGES)/index.html: $(GH_PAGES) publish-build
	@cd $(GH_PAGES) ; \
	  rsync -Cra --delete --exclude=CNAME --exclude=.git ../$(HUGO_OUT)/ . ; \
	  git add .

push:
	@cd $(GH_PAGES) ; \
	  git commit -a -m "pushing docs updates" ; \
	  git pull --rebase ; \
	  git push $${REMOTE_REPO}

publish: $(GH_PAGES)/index.html push

# ── Initial migration (one-time) ──────────────────────────────────────────────
# Clones the morphia repo and converts AsciiDoc → Markdown into branches/.
# Requires pandoc. Run once; edit branches/ directly afterward.
migrate:
	@bash bin/migrate.sh $(BRANCHES)

# ── Utility ───────────────────────────────────────────────────────────────────
clean:
	@rm -rf $(HUGO_OUT) build/javadoc-jars

mrclean: clean
	@rm -rf build $(GH_PAGES)
	@for B in $(BRANCHES); do \
	  VER=$$(cat branches/$$B/.version 2>/dev/null | tr -d '[:space:]') ; \
	  rm -f "content/morphia/$$VER" "content/morphia/$$B" ; \
	done

.PHONY:
