# Morphia Docs — Hugo build system
# Uncomment for verbose debug output:
# __ORIGINAL_SHELL:=$(SHELL)
# SHELL=$(warning [[ Building $@$(if $<, (from $<))$(if $?, ($? newer)) ]] )$(TIME) $(__ORIGINAL_SHELL)

GH_PAGES = gh_pages
HUGO_OUT  = build/site
VERSIONS  = master 2.5.x 2.4.x

default: site

# ── Version discovery ─────────────────────────────────────────────────────────
# Query Maven Central (releases) or the snapshot repo (snapshots) for the
# latest full version for each branch, using content/<branch>/.version for
# the major.minor baseline.  One full version string per line, in VERSIONS order.

versions.list: $(wildcard content/*/.version) bin/syncVersions.kt
	@echo "Discovering versions..."
	@> $@
	@for V in $(VERSIONS); do \
	  jbang bin/syncVersions.kt $$V >> $@ ; \
	done
	@echo "Generated $@"

# ── Version data ──────────────────────────────────────────────────────────────
# Build Hugo's data/versions.yaml by correlating versions.list (full versions)
# with the VERSIONS list and the content/<branch>/.version files.

data/versions.yaml: versions.list
	@echo "# Generated by 'make data/versions.yaml' — do not edit by hand." > $@
	@LATEST=$$(grep -v SNAPSHOT versions.list | sort -V | tail -1) ; \
	echo "latestVersion: \"$$LATEST\"" >> $@ ; \
	echo "versions:" >> $@ ; \
	i=1 ; \
	for V in $(VERSIONS); do \
	  FULL=$$(sed -n "$${i}p" versions.list) ; \
	  MINOR=$$(cat "content/$$V/.version" | tr -d '[:space:]') ; \
	  echo "$$FULL" | grep -q SNAPSHOT && SNAP=true || SNAP=false ; \
	  [ "$$FULL" = "$$LATEST" ] && LAT=true || LAT=false ; \
	  [ "$$V" = "master" ] && DISP="master" || DISP="$$MINOR" ; \
	  printf "  - branch: \"%s\"\n    version: \"%s\"\n    display: \"%s\"\n    latest: %s\n    snapshot: %s\n" \
	    "$$V" "$$FULL" "$$DISP" "$$LAT" "$$SNAP" >> $@ ; \
	  i=$$((i+1)) ; \
	done
	@echo "Generated $@"

# ── Javadoc ───────────────────────────────────────────────────────────────────
# Generate Makefile-javadoc from versions.list (same tool as master branch),
# then execute it.  Javadoc is unpacked to build/site/<minor>/javadoc/ and is
# not committed — it must be present before publishing.

Makefile-javadoc: versions.list bin/generate-makefile.sh
	@bash bin/generate-makefile.sh

javadocs: Makefile-javadoc
	@$(MAKE) -f Makefile-javadoc alldocs

# ── Hugo build ────────────────────────────────────────────────────────────────
$(HUGO_OUT):
	@mkdir -p $@

site: data/versions.yaml javadocs
	@hugo --destination $(HUGO_OUT) --cleanDestinationDir
	@touch $(HUGO_OUT)/.nojekyll
	@echo "Site built → $(HUGO_OUT)"

watch: data/versions.yaml javadocs
	@hugo server --destination $(HUGO_OUT) --bind 0.0.0.0

# ── Branch guard ─────────────────────────────────────────────────────────────
# Publishing and pushing are only permitted when running on the master branch.
# In CI, GITHUB_REF is checked; locally, the current git branch is checked.

guard-master:
	@if [ -n "$${GITHUB_REF}" ]; then \
	  [ "$${GITHUB_REF}" = "refs/heads/master" ] || \
	    { echo "ERROR: publish only runs on master (GITHUB_REF=$${GITHUB_REF})"; exit 1; } ; \
	else \
	  BRANCH=$$(git rev-parse --abbrev-ref HEAD) ; \
	  [ "$$BRANCH" = "master" ] || \
	    { echo "ERROR: publish only runs on master (current branch: $$BRANCH)"; exit 1; } ; \
	fi

# ── gh-pages ─────────────────────────────────────────────────────────────────
$(GH_PAGES): guard-master .PHONY
	@[ ! -d $@ ] && git clone $${REMOTE_REPO} -b gh-pages --depth 1 --no-single-branch $(GH_PAGES) || true
	@git -C $@ reset --hard --quiet && git -C $@ pull --all --quiet

$(GH_PAGES)/index.html: $(GH_PAGES) site
	@cd $(GH_PAGES) ; \
	  rsync -Cra --delete --exclude=CNAME --exclude=.git ../$(HUGO_OUT)/ . ; \
	  git add .

push: guard-master
	@cd $(GH_PAGES) ; \
	  git commit -a -m "pushing docs updates" ; \
	  git pull --rebase ; \
	  git push $${REMOTE_REPO}

publish: guard-master $(GH_PAGES)/index.html push

# ── Utility ───────────────────────────────────────────────────────────────────
clean:
	@rm -rf $(HUGO_OUT) build/javadoc-jars versions.list Makefile-javadoc data/versions.yaml

mrclean: clean
	@rm -rf build $(GH_PAGES)

.PHONY:
