# Morphia Docs — Hugo build system
# Uncomment for verbose debug output:
# __ORIGINAL_SHELL:=$(SHELL)
# SHELL=$(warning [[ Building $@$(if $<, (from $<))$(if $?, ($? newer)) ]] )$(TIME) $(__ORIGINAL_SHELL)

GH_PAGES = gh_pages
HUGO_OUT  = build/site
VERSIONS := $(shell ls -d content/morphia/*/ 2>/dev/null | xargs -n1 basename | sort -Vr | tr '\n' ' ')

default: site

# ── Version discovery ─────────────────────────────────────────────────────────
# Query Maven Central (releases) or the snapshot repo (snapshots) for the
# latest full version for each branch, using content/<branch>/.version for
# the major.minor baseline.  One full version string per line, in VERSIONS order.

versions.list: bin/syncVersions.kt
	@echo "Discovering versions..."
	@> $@
	@for V in $(VERSIONS); do \
	  FULL=$$(jbang bin/syncVersions.kt $$V) ; \
	  echo "$$FULL" >> $@ ; \
	done
	@echo "Generated $@"

# ── Version data ──────────────────────────────────────────────────────────────
# Build Hugo's data/versions.yaml by correlating versions.list (full versions)
# with the VERSIONS list and the content/<branch>/.version files.

data/versions.yaml: versions.list
	@mkdir -p $(dir $@)
	@echo "# Generated by 'make data/versions.yaml' — do not edit by hand." > $@
	@LATEST=$$(jbang bin/syncVersions.kt --latest) ; \
	echo "latestVersion: \"$$LATEST\"" >> $@ ; \
	echo "versions:" >> $@ ; \
	i=1 ; \
	for V in $(VERSIONS); do \
	  FULL=$$(sed -n "$${i}p" versions.list) ; \
	  echo "$$FULL" | grep -q SNAPSHOT && SNAP=true || SNAP=false ; \
	  [ "$$FULL" = "$$LATEST" ] && LAT=true || LAT=false ; \
	  printf "  - branch: \"%s\"\n    version: \"%s\"\n    display: \"%s\"\n    latest: %s\n    snapshot: %s\n" \
	    "$$V" "$$FULL" "$$V" "$$LAT" "$$SNAP" >> $@ ; \
	  i=$$((i+1)) ; \
	done
	@echo "Generated $@"

# ── Javadoc ───────────────────────────────────────────────────────────────────
# Generate Makefile-javadoc from versions.list (same tool as master branch),
# then execute it.  Javadoc is unpacked to build/site/<minor>/javadoc/ and is
# not committed — it must be present before publishing.

Makefile-javadoc: versions.list bin/generate-makefile.sh
	@bash bin/generate-makefile.sh

javadocs: Makefile-javadoc
	@$(MAKE) -f Makefile-javadoc alldocs

# ── Hugo build ────────────────────────────────────────────────────────────────
$(HUGO_OUT):
	@mkdir -p $@

site: data/versions.yaml Makefile-javadoc
	@rm -rf $(HUGO_OUT)
	@hugo --destination $(HUGO_OUT)
	@$(MAKE) -f Makefile-javadoc alldocs
	@touch $(HUGO_OUT)/.nojekyll
	@echo "Site built → $(HUGO_OUT)"

watch: data/versions.yaml
	@hugo server --destination $(HUGO_OUT) --bind 0.0.0.0

# ── Branch guard ─────────────────────────────────────────────────────────────
# Evaluate at parse time: non-empty when on master, empty otherwise.
ifdef GITHUB_REF
  _MASTER := $(filter refs/heads/master,$(GITHUB_REF))
else
  _MASTER := $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null | grep -Fx master)
endif

# ── gh-pages ─────────────────────────────────────────────────────────────────
$(GH_PAGES): .PHONY
	@[ ! -d $@ ] && git clone $${REMOTE_REPO} -b gh-pages --depth 1 --no-single-branch $(GH_PAGES) || true
	@git -C $@ reset --hard --quiet && git -C $@ pull --all --quiet

$(GH_PAGES)/index.html: $(GH_PAGES) site
	@cd $(GH_PAGES) ; \
	  rsync -Cra --delete --exclude=CNAME --exclude=.git ../$(HUGO_OUT)/ . ; \
	  git add .

push:
	@if [ -z "$(_MASTER)" ]; then \
	  echo "Skipping push — not on master branch" ; \
	else \
	  cd $(GH_PAGES) && \
	  git commit -a -m "pushing docs updates" && \
	  git pull --rebase && \
	  git push $${REMOTE_REPO} ; \
	fi

publish: $(if $(_MASTER),$(GH_PAGES)/index.html push)
	@$(if $(_MASTER),,echo "Skipping publish — not on master branch")

# ── Utility ───────────────────────────────────────────────────────────────────
clean:
	@rm -rf $(HUGO_OUT) build/javadoc-jars versions.list Makefile-javadoc data/versions.yaml

mrclean: clean
	@rm -rf build $(GH_PAGES)

.PHONY:
