:page-layout: home-page
:!sectids:

[openblock,"card-row"]
----

[openblock,"column"]
------
== Morphia
MongoDB Object Document Mapping for the JVM

*Bidirectional mapping to and from the database* +
Transparently map your Java entities to MongoDB documents and back. +
*Extensible Type Conversion* +
Easily add support for custom types +
*Robust Query and Update APIs* +
*Full Aggregation Support* +
Use MongoDB's http://docs.mongodb.org/manual/aggregation/[aggregation framework] with your application's Java classes. +
*Annotation driven indexing* +
*Geospatial Queries* +

[openblock,"card-row"]
--------

[openblock,"column"]
----------
xref:morphia:index.adoc[Latest documentation]
----------

[openblock,"column"]
----------
https://github.com/MorphiaOrg/morphia/[Source Code]
----------
--------
------

[openblock,"column"]
------
== Critter
Type safe criteria-builder for use with Morphia-based projects.

*Build time query generated helpers
Check your query definitions at build time
*Curated query and update operators
Only operations that make sense for the field's type are exposed

[openblock,"card-row"]
--------

[openblock,"column"]
----------
<a href="/critter/index.html" class="btn-mongo">Latest documentation</a>
----------

[openblock,"column"]
----------
<a href="https://github.com/MorphiaOrg/morphia/" class="btn-mongo">Source Code</a>
----------

--------
------

----
