name: Docs

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out gh_pages
        uses: actions/checkout@v2
        with:
          repository: MorphiaOrg/morphia
          ref: gh-pages
          path: gh_pages
          token: ${{ secrets.PUSH_TOKEN }}
      - name: User Info
        run: |
          cd gh_pages
          git config user.name evanchooly
          git config user.email jlee@antwerkz.com
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Antora
        env:
          REMOTE_REPO: https://evanchooly:${{ secrets.PUSH_TOKEN }}@github.com/MorphiaOrg/morphia.git
        run: make clean publish
