name: Docs

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out gh_pages
        uses: actions/checkout@v2
        with:
          repository: MorphiaOrg/morphia
          ref: gh_pages
          path: gh_pages
      - name: Run antora
        run: make publish