name: Docs

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out gh_pages
        uses: actions/checkout@v2
        with:
          repository: MorphiaOrg/morphia
          ref: gh-pages
          path: gh_pages
          token: ${{ secrets.PUSHTOKEN }}
      - name: Run Antora
        env:
          REMOTE_REPO: https://evanchooly:${{ secrets.PUSHTOKEN }}@github.com/MorphiaOrg/morphia.git
        run: make publish