name: Docs

# on:
  # push:
  # workflow_dispatch:
  # schedule:
    # - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: false

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Configure git identity
        run: |
          git config --global user.name evanchooly
          git config --global user.email jlee@antwerkz.com

      - name: Stage content
        run: make stage-content

      - name: Build site
        run: make site

      - name: Download Javadoc
        run: make javadocs

      - name: Sync to gh-pages
        env:
          REMOTE_REPO: https://evanchooly:${{ secrets.GH_PUSH_TOKEN }}@github.com/MorphiaOrg/morphia-docs.git
        run: make publish
