name: Docs

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out gh_pages
        uses: actions/checkout@v2
        with:
          repository: MorphiaOrg/morphia
          ref: gh-pages
          path: gh_pages
      - name: User Info
        run: |
          cd gh_pages
          git config user.name evanchooly
          git config user.email jlee@antwerkz.com
      - name: Run Antora
        run: make publish