name: Docs

on:
  push:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: User Info
        run: |
          cd gh_pages
          git config user.name evanchooly
          git config user.email jlee@antwerkz.com
      - name: Run Antora
        env:
          REMOTE_REPO: https://evanchooly:${{ secrets.PUSH_TOKEN }}@github.com/MorphiaOrg/morphia.git
        run: make clean publish
