name: Docs

on:
  push:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup JBang
        uses: jbangdev/setup-jbang@main
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: User Info
        run: |
          git config --global user.name evanchooly
          git config --global user.email jlee@antwerkz.com
      - name: Run Antora
        env:
          REMOTE_REPO: https://evanchooly:${{ secrets.GH_PUSH_TOKEN }}@github.com/MorphiaOrg/morphia.git
        run: make clean publish
